#!/usr/bin/env python3

"""
Plots data from the CSV file generated by `scripts/experiments/test-compression.py`,
displaying the results on screen.
"""

import argparse
import csv
from matplotlib.lines import Line2D
import matplotlib.pyplot as plt
from matplotlib.ticker import FormatStrFormatter, FuncFormatter, MaxNLocator
import os
from sys import stderr

HEADERS = (
    'mtype', 'comp', 'class',
    'acc_all', 'tpr_all', 'tnr_all',
    'acc_c0', 'tpr_c0', 'tnr_c0',
    'acc_c23', 'tpr_c23', 'tnr_c23',
    'acc_c40', 'tpr_c40', 'tnr_c40'
)

HINDEX = {v: i for i, v in enumerate(HEADERS)}

CLASSES = ('f2f', 'df', 'fs', 'icf', 'gann', 'x2f')

CLASS_TO_LABEL = {
    'f2f'  : 'Face2Face',
    'df'   : 'Deepfakes',
    'fs'   : 'FaceSwap',
    'icf'  : 'ICface',
    'gann' : 'GANnotation',
    'x2f'  : 'X2Face'
}

CLASS_TO_COLOR = {
    'f2f' : (0, 1, 0),      # Green
    'df'  : (1, 0, 0),      # Red
    'fs'  : (0, 1, 1),      # Cyan
    'icf' : (1, 0.6, 0),    # Orange
    'gann': (1, 0.7, 0.8),  # Pink
    'x2f' : (0, 0, 1)       # Blue
}

COMP_TO_LINESTYLE = {
    'c0'  : '--',
    'c23' : '-.',
    'c40' : ':',
    'all' : '-'
}

'''
COMP_TO_LABEL = {
    'c0'  : 'Lossless',
    'c23' : 'Visibly lossless',
    'c40' : 'Lossy',
    'all' : 'All'
}
'''
COMP_TO_LABEL = {
    'c0'  : 'Trained on lossless',
    'c23' : 'Trained on visibly lossless',
    'c40' : 'Trained on lossy',
    'all' : 'Trained on all'
}

X_LABELS = ('Lossless', 'Visibly lossless', 'Lossy', 'All')

def x_to_comp(tick_val, tick_pos):
    """
    A formatting function for `matplotlib.ticker.FuncFormatter`.
    """
    if tick_val >= 0 and tick_val < len(X_LABELS):
        return X_LABELS[int(tick_val)]
    else:
        return ''

def load_model_data(csv_path):
    """
    Loads model results from a CSV file created by
    `scripts/experiments/test-compression.py`.

    Args:
        csv_path: Path to CSV file.

    Returns:
        A dictionary mapping model name -> class -> trained compression level
            -> tested compression level -> {accuracy, TPR, TNR}.
    """
    models = {}
    with open(csv_path, 'r') as f:
        reader = csv.reader(f, delimiter=',', quotechar='"')

        # Skip the headers.
        next(reader)

        comps = ('c0', 'c23', 'c40', 'all')
        for row in reader:
            mtype = row[HINDEX['mtype']]
            class_type = row[HINDEX['class']]
            train_comp = row[HINDEX['comp']]

            if mtype not in models:
                models[mtype] = {}
            if class_type not in models[mtype]:
                models[mtype][class_type] = {}

            test_results = {}
            for test_comp in ('c0', 'c23', 'c40', 'all'):
                res = {}
                for metric in ('acc', 'tpr', 'tnr'):
                    label = '{}_{}'.format(metric, test_comp)
                    res[metric] = row[HINDEX[label]]
                test_results[test_comp] = res

            models[mtype][class_type][train_comp] = test_results

    return models

def plot_accuracy(models):
    """
    Plots accuracies for each compression level.

    Args:
        models: A dictionary returned by `load_model_data`.

    Returns:
        Matplotlib figure and axes.
    """
    # Plot accuracy of models against each compression level.
    fig, ax = plt.subplots()
    ax.set_xlabel('Compression level')
    ax.set_ylabel('Accuracy')
    ax.xaxis.set_major_formatter(FuncFormatter(x_to_comp))
    ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    xs = (0, 1, 2, 3)
    leg_handles = []
    leg_labels = []
    for mtype in models:
        model = models[mtype]
        for class_type in CLASSES:
            if class_type not in model:
                continue
            color = CLASS_TO_COLOR[class_type]
            for train_comp in model[class_type]:
                res = model[class_type][train_comp]
                label = '{}, {}'.format(class_type, train_comp)
                ys = (res['c0']['acc'], res['c23']['acc'], res['c40']['acc'], res['all']['acc'])
                ys = [float(y) for y in ys]
                linstyle = COMP_TO_LINESTYLE[train_comp]
                ax.plot(xs, ys, linstyle, label=label, color=color)

            # Create custom legend entries.  Only want to show one entry
            # for each class type.
            leg_handles.append(
                Line2D([], [], linestyle=COMP_TO_LINESTYLE['all'], color=color))
            leg_labels.append(CLASS_TO_LABEL[class_type])

    # Draw lines marking each compression level.
    for x in xs:
        plt.axvline(x=x, linestyle='-', color=(0, 0, 0, 0.1))

    # Add legend entries for line styles.
    for comp in COMP_TO_LINESTYLE:
        linstyle = COMP_TO_LINESTYLE[comp]
        leg_handles.append(Line2D([], [], linestyle=linstyle, color=(0, 0, 0)))
        leg_labels.append(COMP_TO_LABEL[comp])

    ax.legend(leg_handles, leg_labels)

    return fig, ax

def plot_tpr_vs_tnr(models):
    """
    Plots the ratios of true positive rates to true negative rates for each
    compression level.

    Args:
        models: A dictionary returned by `load_model_data`.

    Returns:
        Matplotlib figure and axes.
    """
    fig, ax = plt.subplots()
    ax.set_xlabel('Compression level')
    ax.set_ylabel('TPR to TNR ratio')
    ax.xaxis.set_major_formatter(FuncFormatter(x_to_comp))
    ax.xaxis.set_major_locator(MaxNLocator(integer=True))
    ax.set_yscale('log')
    ax.tick_params(axis='y', which='minor')
    ax.tick_params(axis='y', which='major')
    ax.yaxis.set_minor_formatter(FormatStrFormatter('%.1f'))
    ax.yaxis.set_major_formatter(FormatStrFormatter('%.1f'))
    xs = (0, 1, 2, 3)
    leg_handles = []
    leg_labels = []
    for mtype in models:
        model = models[mtype]
        for class_type in CLASSES:
            if class_type not in model:
                continue
            color = CLASS_TO_COLOR[class_type]
            for train_comp in model[class_type]:
                res = model[class_type][train_comp]
                tprs = (res['c0']['tpr'], res['c23']['tpr'], res['c40']['tpr'], res['all']['tpr'])
                tnrs = (res['c0']['tnr'], res['c23']['tnr'], res['c40']['tnr'], res['all']['tnr'])
                ratios = [float(tprs[i]) / float(tnrs[i]) for i in range(len(tprs))]
                linstyle = COMP_TO_LINESTYLE[train_comp]
                ax.plot(xs, ratios, linstyle, color=color)

            # Create custom legend entries.  Only want to show one entry
            # for each class type.
            leg_handles.append(
                Line2D([], [], linestyle=COMP_TO_LINESTYLE['all'], color=color))
            leg_labels.append(CLASS_TO_LABEL[class_type])

    # Draw lines marking each compression level and the ideal ratio.
    for x in xs:
        plt.axvline(x=x, linestyle='-', color=(0, 0, 0, 0.1))
    plt.axhline(y=1, linestyle='-', color=(0, 0, 0, 0.1))

    # Add legend entries for line styles.
    for comp in COMP_TO_LINESTYLE:
        linstyle = COMP_TO_LINESTYLE[comp]
        leg_handles.append(Line2D([], [], linestyle=linstyle, color=(0, 0, 0)))
        leg_labels.append(COMP_TO_LABEL[comp])

    # Hide every other minor tick label.
    for label in ax.get_yticklabels(which='minor')[1::2]:
        label.set_visible(False)

    ax.legend(leg_handles, leg_labels)

    return fig, ax

def main(csv_path):
    """
    Creates and displays various plots using the supplied experimentation data.
    """

    models = load_model_data(csv_path)

    acc_fig, acc_ax = plot_accuracy(models)

    # Plot TPR vs. TNR of models against each compression level.
    vs_fig, vs_ax = plot_tpr_vs_tnr(models)
    plt.show()

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Tests a model')
    parser.add_argument('input', type=str, nargs=1,
                        help='path to CSV file with compression data')
    args = parser.parse_args()

    csv_path = args.input[0]

    if not os.path.isfile(csv_path):
        print('"{}" is not a file'.format(csv_path), file=stderr)
        exit(2)

    main(csv_path)
